### ISSUE TITLE
How can change color code in css?

### ISSUE THREAD

**Issue by GLY-JeffreyTCK** [domske/state-stepper#7]
Hi, can change color code in ionic?

**Comment by domske** [comment]
You could override the css color variables like:

```css
state-stepper-step {
  --color-idle: #000; 
  --color-active: #f00;
  /* etc */
}
```

Available css variables: 

```css
  --size: 60px;
  --color-idle: #989aa2;
  --color-idle-contrast: #ffffff;
  --color-success: #10dc60;
  --color-success-contrast: #ffffff;
  --color-warning: #ffce00;
  --color-warning-contrast: #ffffff;
  --color-danger: #f04141;
  --color-danger-contrast: #ffffff;
  --color-active: #3880ff;
  --color-active-contrast: #ffffff;
```
